apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: provisioning-graviton
spec:
  template:
    metadata:
      labels:
        type: karpenter
        workload-type: provisioning
        arch: arm64
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "c", "m"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["3"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["small", "medium", "large", "xlarge"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: provisioning-graviton
      expireAfter: 720h # 30 days
  limits:
    cpu: 100
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: provisioning-graviton
spec:
  tags:
    KarpenterProvisionerName: "provisioning-graviton"
    NodeType: "provisioning"
    Cluster: "test-s4"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
  role: "KarpenterNodeRole-test-s4"
  amiSelectorTerms:
    - alias: "al2023@latest"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "test-s4"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "test-s4"
